[package]
name = "mcpgw"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
mcpgw-core.workspace = true
clap.workspace = true
anyhow.workspace = true
serde_json.workspace = true
owo-colors.workspace = true
which.workspace = true
tokio.workspace = true
tempfile.workspace = true

[dev-dependencies]
insta.workspace = true
assert_cmd.workspace = true

[lints]
workspace = true
