//! The systemd `--user` backend: the unit text it writes, the commands it
//! runs, and what it says on a machine that has no systemd.
//!
//! Every `systemctl`/`loginctl` call goes through an injected runner, so the
//! whole file runs (and means something) on a developer machine that has
//! never seen a unit file. The one thing it cannot cover is systemd itself
//! accepting the unit; that is what CI's Linux job and dogfooding are for.
#![cfg(not(any(target_os = "macos", windows)))]

use std::cell::RefCell;
use std::ffi::OsString;
use std::path::{Path, PathBuf};

use mcpgw_core::daemon::systemd::{
    Linger, Ran, install_with, linger, linger_note, query_with, render_unit, start_with, stop_with,
    uninstall_with, unit_path_with,
};
use mcpgw_core::daemon::{DaemonError, DaemonSpec, LogPaths};

fn spec(state_dir: &Path) -> DaemonSpec {
    DaemonSpec {
        exe: PathBuf::from("/usr/local/bin/mcpgw"),
        config_path: PathBuf::from("/home/u/.config/mcpgw/config.toml"),
        state_dir: state_dir.to_owned(),
        bind: "127.0.0.1".to_owned(),
        port: 8137,
        logs: LogPaths::under_state_dir(state_dir),
    }
}

/// A recording runner: answers from `replies` (matched on the first argument
/// that is not a flag) and remembers every command line it was handed.
struct Fake {
    calls: RefCell<Vec<String>>,
    replies: Vec<(&'static str, std::io::Result<Ran>)>,
}

impl Fake {
    fn new(replies: Vec<(&'static str, std::io::Result<Ran>)>) -> Self {
        Self {
            calls: RefCell::new(Vec::new()),
            replies,
        }
    }

    fn exec(&self) -> impl Fn(&str, &[&str]) -> std::io::Result<Ran> + '_ {
        move |program, args| {
            self.calls
                .borrow_mut()
                .push(format!("{program} {}", args.join(" ")));
            let verb = args
                .iter()
                .find(|arg| !arg.starts_with('-'))
                .copied()
                .unwrap_or_default();
            for (key, reply) in &self.replies {
                if *key == verb {
                    return match reply {
                        Ok(ran) => Ok(ran.clone()),
                        Err(err) => Err(std::io::Error::new(err.kind(), err.to_string())),
                    };
                }
            }
            Ok(Ran::ok(""))
        }
    }

    fn calls(&self) -> Vec<String> {
        self.calls.borrow().clone()
    }
}

fn missing() -> std::io::Result<Ran> {
    Err(std::io::Error::new(
        std::io::ErrorKind::NotFound,
        "No such file or directory (os error 2)",
    ))
}

fn env(pairs: &[(&str, &str)]) -> impl Fn(&str) -> Option<OsString> {
    let pairs: Vec<(String, String)> = pairs
        .iter()
        .map(|(key, value)| ((*key).to_owned(), (*value).to_owned()))
        .collect();
    move |key| {
        pairs
            .iter()
            .find(|(known, _)| known == key)
            .map(|(_, value)| OsString::from(value))
    }
}

/// The unit is the whole product on Linux, so it is compared byte for byte
/// rather than probed for substrings: a directive that quietly changes shape
/// is a service that quietly stops coming back at login.
#[test]
fn the_unit_is_rendered_exactly() {
    let unit = render_unit(
        &spec(Path::new("/home/u/.local/share/mcpgw")),
        Some("/home/u/.local/bin:/usr/bin:/bin"),
    );

    assert_eq!(
        unit,
        concat!(
            "# Generated by `mcpgw daemon install`; edits are overwritten by the next install.\n",
            "[Unit]\n",
            "Description=mcpgw MCP gateway\n",
            "Documentation=https://github.com/kennywillbe/mcpgw\n",
            "\n",
            "[Service]\n",
            "Type=simple\n",
            "Environment=MCPGW_CONFIG=/home/u/.config/mcpgw/config.toml\n",
            "Environment=MCPGW_STATE_DIR=/home/u/.local/share/mcpgw\n",
            "Environment=PATH=/home/u/.local/bin:/usr/bin:/bin\n",
            "ExecStart=/usr/local/bin/mcpgw serve --bind 127.0.0.1 --port 8137\n",
            "Restart=on-failure\n",
            "RestartSec=2\n",
            "StandardOutput=append:/home/u/.local/share/mcpgw/logs/daemon.out.log\n",
            "StandardError=append:/home/u/.local/share/mcpgw/logs/daemon.err.log\n",
            "\n",
            "[Install]\n",
            "WantedBy=default.target\n",
        )
    );
}

/// No `PATH` to inherit is not a reason to write an empty one: a unit with
/// `Environment=PATH=` would leave every stdio server unspawnable, which is
/// worse than the manager's own default.
#[test]
fn without_a_path_to_inherit_the_unit_has_no_path_line() {
    let unit = render_unit(&spec(Path::new("/home/u/.local/share/mcpgw")), None);

    assert!(!unit.contains("PATH"), "{unit}");
    assert!(unit.contains("\nEnvironment=MCPGW_STATE_DIR="), "{unit}");
}

#[test]
fn a_space_is_quoted_and_a_percent_is_doubled_for_the_unit_parser() {
    let mut spec = spec(Path::new("/home/100% sure/state"));
    spec.exe = PathBuf::from("/opt/my tools/mcpgw");
    spec.config_path = PathBuf::from("/home/100% sure/config.toml");

    let unit = render_unit(&spec, Some("/home/100% sure/bin"));

    assert!(
        unit.contains("ExecStart=\"/opt/my tools/mcpgw\" serve --bind 127.0.0.1 --port 8137\n"),
        "{unit}"
    );
    assert!(
        unit.contains("Environment=\"MCPGW_CONFIG=/home/100%% sure/config.toml\"\n"),
        "{unit}"
    );
    assert!(
        unit.contains("Environment=\"PATH=/home/100%% sure/bin\"\n"),
        "{unit}"
    );
    assert!(
        unit.contains("StandardOutput=append:/home/100%% sure/state/logs/daemon.out.log\n"),
        "{unit}"
    );
}

#[test]
fn install_writes_the_unit_then_reloads_then_enables_and_restarts_it() {
    let dir = tempfile::tempdir().unwrap();
    let unit_path = dir.path().join("systemd/user/mcpgw.service");
    let fake = Fake::new(vec![("show-user", Ok(Ran::ok("Linger=yes")))]);

    let installed = install_with(
        &spec(dir.path()),
        &unit_path,
        &fake.exec(),
        env(&[("USER", "u"), ("PATH", "/opt/bin")]),
    )
    .unwrap();

    assert_eq!(installed.unit_path, unit_path);
    // The PATH the install ran with is what the service gets, so the unit on
    // disk has to be the one rendered from it.
    assert_eq!(
        std::fs::read_to_string(&unit_path).unwrap(),
        render_unit(&spec(dir.path()), Some("/opt/bin"))
    );
    // The reload must come first: systemd will not enable a unit it has not
    // read yet. The restart is what makes a reinstall land on the binary the
    // new definition names, rather than leaving the old process serving.
    assert_eq!(
        fake.calls()[..3],
        [
            "systemctl --user daemon-reload".to_owned(),
            "systemctl --user enable mcpgw.service".to_owned(),
            "systemctl --user restart mcpgw.service".to_owned(),
        ]
    );
    // The three things an install leaves a user needing to know: whether it
    // survives logout, that the config and PATH are frozen into the unit, and
    // where the output went.
    let notes = installed.notes.join("\n");
    assert!(notes.contains("it serves "), "{notes}");
    assert!(notes.contains("PATH you installed from"), "{notes}");
    assert!(notes.contains("mcpgw daemon logs --follow"), "{notes}");
    assert!(
        installed
            .notes
            .iter()
            .any(|note| note.contains("keeps running after you log out")),
        "{:?}",
        installed.notes
    );
}

#[test]
fn an_install_systemd_refuses_reports_what_systemd_said() {
    let dir = tempfile::tempdir().unwrap();
    let fake = Fake::new(vec![(
        "enable",
        Ok(Ran::failed("Failed to enable unit: Unit file is masked.")),
    )]);

    let err = install_with(
        &spec(dir.path()),
        &dir.path().join("mcpgw.service"),
        &fake.exec(),
        env(&[]),
    )
    .unwrap_err();

    let text = err.to_string();
    assert!(matches!(err, DaemonError::Service { .. }), "{text}");
    assert!(text.contains("Unit file is masked"), "{text}");
    assert!(text.contains("systemd --user"), "{text}");
}

/// The non-systemd distributions: `systemctl` is simply not there, and every
/// entry point has to say so in a sentence rather than surface an errno.
#[test]
fn a_machine_without_systemctl_is_told_what_to_do_instead() {
    let dir = tempfile::tempdir().unwrap();
    let unit_path = dir.path().join("mcpgw.service");
    std::fs::write(&unit_path, "placeholder").unwrap();
    let fake = Fake::new(vec![
        ("daemon-reload", missing()),
        ("enable", missing()),
        ("start", missing()),
        ("stop", missing()),
        ("is-active", missing()),
        ("disable", missing()),
    ]);
    let exec = fake.exec();

    let errors = [
        install_with(&spec(dir.path()), &unit_path, &exec, env(&[])).map(|_| ()),
        uninstall_with(&unit_path, &exec),
        start_with(&unit_path, &exec),
        stop_with(&exec),
        query_with(&unit_path, &exec, env(&[])).map(|_| ()),
    ];

    for error in errors {
        let text = error.unwrap_err().to_string();
        assert!(
            text.contains("does not appear to be running systemd"),
            "{text}"
        );
        assert!(text.contains("mcpgw serve"), "{text}");
    }
}

/// Nothing installed and no systemd: the end state uninstall promises is
/// already true, so it is not an error.
#[test]
fn uninstalling_nothing_succeeds_even_without_systemctl() {
    let dir = tempfile::tempdir().unwrap();
    let fake = Fake::new(vec![("disable", missing())]);

    uninstall_with(&dir.path().join("mcpgw.service"), &fake.exec()).unwrap();
}

#[test]
fn uninstall_removes_the_unit_and_reloads_even_when_it_was_not_loaded() {
    let dir = tempfile::tempdir().unwrap();
    let unit_path = dir.path().join("mcpgw.service");
    std::fs::write(&unit_path, "placeholder").unwrap();
    let fake = Fake::new(vec![(
        "disable",
        Ok(Ran::failed(
            "Failed to disable unit: Unit file does not exist.",
        )),
    )]);

    uninstall_with(&unit_path, &fake.exec()).unwrap();

    assert!(!unit_path.exists());
    assert_eq!(
        fake.calls(),
        [
            "systemctl --user disable --now mcpgw.service".to_owned(),
            "systemctl --user daemon-reload".to_owned(),
        ]
    );
}

#[test]
fn starting_without_a_unit_points_at_install_rather_than_at_systemd() {
    let dir = tempfile::tempdir().unwrap();
    let fake = Fake::new(Vec::new());

    let err = start_with(&dir.path().join("mcpgw.service"), &fake.exec()).unwrap_err();

    let text = err.to_string();
    assert!(text.contains("mcpgw daemon install"), "{text}");
    assert!(fake.calls().is_empty(), "{:?}", fake.calls());
}

#[test]
fn query_reports_a_running_enabled_unit_and_where_it_lives() {
    let dir = tempfile::tempdir().unwrap();
    let unit_path = dir.path().join("mcpgw.service");
    std::fs::write(&unit_path, "placeholder").unwrap();
    let fake = Fake::new(vec![
        ("is-active", Ok(Ran::ok("active"))),
        ("is-enabled", Ok(Ran::ok("enabled"))),
        ("show-user", Ok(Ran::ok("Linger=no"))),
    ]);

    let status = query_with(&unit_path, &fake.exec(), env(&[("USER", "u")])).unwrap();

    assert!(status.installed);
    assert!(status.running);
    assert_eq!(status.unit_path, Some(unit_path));
    let detail = status.detail.unwrap();
    assert!(detail.contains("comes back at login"), "{detail}");
    assert!(detail.contains("loginctl enable-linger u"), "{detail}");
}

/// systemd exits non-zero for "inactive" and "disabled". Those are answers,
/// not failures, and reading them as failures would make `daemon status`
/// error out on the most ordinary state there is.
#[test]
fn an_inactive_disabled_unit_is_a_status_and_not_an_error() {
    let dir = tempfile::tempdir().unwrap();
    let unit_path = dir.path().join("mcpgw.service");
    std::fs::write(&unit_path, "placeholder").unwrap();
    let fake = Fake::new(vec![
        ("is-active", Ok(Ran::failed("inactive"))),
        ("is-enabled", Ok(Ran::ok("disabled"))),
    ]);

    let status = query_with(&unit_path, &fake.exec(), env(&[])).unwrap();

    assert!(status.installed);
    assert!(!status.running);
    assert!(
        status
            .detail
            .unwrap()
            .contains("will not come back at login"),
        "disabled has to be visible in status, not swallowed"
    );
}

#[test]
fn nothing_installed_is_the_empty_status() {
    let dir = tempfile::tempdir().unwrap();
    let fake = Fake::new(vec![("is-enabled", Ok(Ran::failed("not-found")))]);

    let status = query_with(&dir.path().join("mcpgw.service"), &fake.exec(), env(&[])).unwrap();

    assert_eq!(status, mcpgw_core::daemon::ServiceStatus::default());
}

/// A unit installed by hand into a directory this build does not write to is
/// still an installed unit; systemd's answer is what decides.
#[test]
fn a_unit_systemd_knows_about_counts_as_installed_without_our_file() {
    let dir = tempfile::tempdir().unwrap();
    let fake = Fake::new(vec![
        ("is-active", Ok(Ran::ok("active"))),
        ("is-enabled", Ok(Ran::ok("static"))),
    ]);

    let status = query_with(&dir.path().join("mcpgw.service"), &fake.exec(), env(&[])).unwrap();

    assert!(status.installed);
    assert!(status.running);
}

#[test]
fn linger_reads_the_property_and_treats_every_other_answer_as_unknown() {
    let cases = [
        (Ok(Ran::ok("Linger=yes")), Linger::On),
        (Ok(Ran::ok("Linger=no")), Linger::Off),
        (Ok(Ran::ok("")), Linger::Unknown),
        (
            Ok(Ran::failed("Failed to get user: No such user")),
            Linger::Unknown,
        ),
        (missing(), Linger::Unknown),
    ];

    for (reply, expected) in cases {
        let fake = Fake::new(vec![("show-user", reply)]);
        assert_eq!(linger(&fake.exec(), Some("u")), expected);
        assert_eq!(
            fake.calls(),
            ["loginctl show-user u --property=Linger".to_owned()]
        );
    }
}

#[test]
fn no_user_name_in_the_environment_never_asks_loginctl() {
    let fake = Fake::new(vec![("show-user", Ok(Ran::ok("Linger=yes")))]);

    assert_eq!(linger(&fake.exec(), None), Linger::Unknown);
    assert!(fake.calls().is_empty(), "{:?}", fake.calls());
}

/// The note is the only place a user learns their gateway dies at logout, so
/// each of the three answers has to produce a different sentence — and the
/// two that are not "on" have to name the command that fixes it.
#[test]
fn the_linger_note_says_which_of_the_three_states_this_is() {
    let on = Fake::new(vec![("show-user", Ok(Ran::ok("Linger=yes")))]);
    let note = linger_note(&on.exec(), env(&[("USER", "u")]));
    assert!(note.contains("keeps running after you log out"), "{note}");
    assert!(!note.contains("enable-linger"), "{note}");

    let off = Fake::new(vec![("show-user", Ok(Ran::ok("Linger=no")))]);
    let note = linger_note(&off.exec(), env(&[("LOGNAME", "u")]));
    assert!(note.contains("stops when your last session ends"), "{note}");
    assert!(note.contains("loginctl enable-linger u"), "{note}");
    // Reporting, not doing: the note has to say mcpgw left the account alone.
    assert!(note.contains("does not run it for you"), "{note}");

    let absent = Fake::new(vec![("show-user", missing())]);
    let note = linger_note(&absent.exec(), env(&[]));
    assert!(note.contains("could not ask loginctl"), "{note}");
    assert!(note.contains("loginctl enable-linger $USER"), "{note}");
}

#[test]
fn the_unit_goes_where_systemctl_user_looks_for_it() {
    assert_eq!(
        unit_path_with(env(&[("XDG_CONFIG_HOME", "/xdg"), ("HOME", "/home/u")])),
        Some(PathBuf::from("/xdg/systemd/user/mcpgw.service"))
    );
    assert_eq!(
        unit_path_with(env(&[("HOME", "/home/u")])),
        Some(PathBuf::from("/home/u/.config/systemd/user/mcpgw.service"))
    );
    assert_eq!(
        unit_path_with(env(&[("XDG_CONFIG_HOME", ""), ("HOME", "/home/u")])),
        Some(PathBuf::from("/home/u/.config/systemd/user/mcpgw.service"))
    );
    assert_eq!(unit_path_with(env(&[])), None);
}
